name: Update bun.lockb

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-bun-lockb:
    name: "Update bun.lockb"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies with Bun
        run: bun install

      - name: Commit and push changes to bun.lockb
        run: |
          git add bun.lockb
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Update bun.lockb (via GitHub Actions)"
          git pull --rebase origin main
          git push
