name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        run: echo "${{ github.event.head_commit.message }}" | grep -qi "build" || exit 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Zip Build Artifact
        run: zip -r dist.zip ./dist/*

      - name: Verify Zip File
        run: ls -l dist.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
